name: Build document

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        sources:
          - ctfp-print.tex
          - ctfp-reader.tex
          - ctfp-print-scala.tex
          - ctfp-reader-scala.tex
          - ctfp-print-ocaml.tex
          - ctfp-reader-ocaml.tex

    steps:
      - name: Build documents using LaTeX (default)
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          latexmk_use_xelatex: true
          root_file: ${{ matrix.sources }}
          latexmk_shell_escape: true


  release:
    name: "Create Github tag/pre-release"
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Create Github pre-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Version ${{ env.VERSION }}
          draft: false
          prerelease: true

  assets:
    name: Upload release asset (print)
    needs: release
    strategy:
      matrix:
        destination:
          - source: src/ctfp-print.pdf
            destination: category-theory-for-programmers--print--${{ env.VERSION }}
          - source: src/ctfp-reader.pdf
            destination: category-theory-for-programmers--${{ env.VERSION }}
          - source: src/ctfp-print-scala.pdf
            destination: category-theory-for-programmers--print--scala--${{ env.VERSION }}
          - source: src/ctfp-reader-scala.pdf
            destination: category-theory-for-programmers--reader--scala--${{ env.VERSION }}
          - source: src/ctfp-print-ocaml.pdf
            destination: category-theory-for-programmers--print--ocaml--${{ env.VERSION }}
          - source: src/ctfp-reader-ocaml.pdf
            destination: category-theory-for-programmers--reader--ocaml--${{ env.VERSION }}

    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ jobs.release.steps.create_release.outputs.upload_url }}
      asset_path: ${{ matrix.source }}
      asset_name: ${{ matrix.destination }}
      asset_content_type: application/pdf
