name: Build document

on:
  - push

jobs:
  dependencies:
    name: Build dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Create global variables
        run: |
          echo "::set-output name=version::$(git rev-parse --short HEAD)"

      - name: Create necessary build file
        run: |
          echo -n -e "\\\newcommand{\OPTversion}{$(git rev-parse --short HEAD)}" > src/version.tex

  build:
    name: Build documents
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sources:
          - ctfp-print.tex
          - ctfp-reader.tex
          - ctfp-print-scala.tex
          - ctfp-reader-scala.tex
          - ctfp-print-ocaml.tex
          - ctfp-reader-ocaml.tex

    steps:
      - name: Build documents using LaTeX (default)
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          latexmk_use_xelatex: true
          root_file: ${{ matrix.sources }}
          latexmk_shell_escape: true

  release:
    name: "Create Github tag/pre-release"
    runs-on: ubuntu-latest
    needs: [dependencies,build]
    outputs:
      upload_url: ${{ steps.create_release.upload_url }}
    steps:
      - name: Create Github pre-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.dependencies.outputs.version }}
          release_name: Version ${{ needs.dependencies.outputs.version }}
          draft: false
          prerelease: true

  assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [dependencies,release]
    strategy:
      matrix:
        destination:
          - source: src/ctfp-print.pdf
            destination: category-theory-for-programmers--print--
          - source: src/ctfp-reader.pdf
            destination: category-theory-for-programmers--
          - source: src/ctfp-print-scala.pdf
            destination: category-theory-for-programmers--print--scala--
          - source: src/ctfp-reader-scala.pdf
            destination: category-theory-for-programmers--reader--scala--
          - source: src/ctfp-print-ocaml.pdf
            destination: category-theory-for-programmers--print--ocaml--
          - source: src/ctfp-reader-ocaml.pdf
            destination: category-theory-for-programmers--reader--ocaml--
    steps:
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ matrix.source }}
          asset_name: ${{ matrix.destination }}${{ needs.dependencies.outputs.version }}.pdf
          asset_content_type: application/pdf
